In [15]:
import pandas as pd
import numpy as np
import psutil
from unidecode import unidecode
from fuzzywuzzy import fuzz
from collections import defaultdict
import json

# Check memory usage
def memory_usage():
    process = psutil.Process()
    mem_info = process.memory_info()
    return mem_info.rss / (1024 * 1024)  # Convert bytes to MB

print(f"Memory usage: {memory_usage()} MB")

Memory usage: 164.578125 MB

In [2]:
# Set pandas display options
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.max_colwidth', None)  # Show full column width
pd.set_option('display.expand_frame_repr', False)  # Disable wrapping of rows

In [ ]:
main = pd.read_csv('./classifier_positions.csv', encoding='utf-8', sep=',', header=None)
main.columns = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"]

   1   2   3  4   5                                                                        6                                                                                     7     8  9     10    11       12                                                                                           13 14  15
0  1 NaN  1.  1  C8                                                              Авербандщик                                                                            Авербандчи  8264  П  2 — 5  ССПО  3320900                                                                                  Averbandchi  i   1
1  2 NaN  2.  2  C8  Авиационный механик (техник) по обслуживанию и ремонту воздушных судов.  Ҳаво кемаларига хизмат кўрсатиш ва уларни таъмирлаш бўйича авиация механиги (техник)  7232  П  2 — 6  ССПО  3310400  havo kemalariga xizmat ko‘rsatish va ularni ta’mirlash bo‘yicha aviatsiya mexanigi (texnik)  i   2
2  3 NaN  3.  3  C8         Авиационный механик перронно-технической бригады (ПТБ) аэропорта                                    Аэропорт перрон-техника бригадаси авиация механиги  7232  П  2 — 6  ССПО  3310400                                         Aeroport perron-texnika brigadasi aviatsiya mexanigi  i   3
3  4 NaN  4.  4  C8                     Авиационный механик (техник) по планеру и двигателям                                Планер ва двигателлар бўйича авиация механиги (техник)  7232  П  2 — 6  ССПО  3310400                                   Planer va dvigatellar bo‘yicha aviatsiya mexanigi (texnik)  i   4
4  5 NaN  5.  5  C8           Авиационный механик (техник) по приборам и электрооборудованию                         Приборлар ва электр жихозлар бўйича авиация механиги (техник)  7232  П  2 — 6  ССПО  3310400                           Priborlar va elektr jixoz lar bo‘yicha aviatsiya mexanigi (texnik)  i   5

In [7]:
main.head(50)

     1   2    3   4   5                                                                                    6                                                                                          7     8  9     10    11                                        12                                                                                                   13 14  15
0    1 NaN   1.   1  C8                                                                          Авербандщик                                                                                 Авербандчи  8264  П  2 — 5  ССПО                                   3320900                                                                                          Averbandchi  i   1
1    2 NaN   2.   2  C8              Авиационный механик (техник) по обслуживанию и ремонту воздушных судов.       Ҳаво кемаларига хизмат кўрсатиш ва уларни таъмирлаш бўйича авиация механиги (техник)  7232  П  2 — 6  ССПО                                   3310400          havo kemalariga xizmat ko‘rsatish va ularni ta’mirlash bo‘yicha aviatsiya mexanigi (texnik)  i   2
2    3 NaN   3.   3  C8                     Авиационный механик перронно-технической бригады (ПТБ) аэропорта                                         Аэропорт перрон-техника бригадаси авиация механиги  7232  П  2 — 6  ССПО                                   3310400                                                 Aeroport perron-texnika brigadasi aviatsiya mexanigi  i   3
3    4 NaN   4.   4  C8                                 Авиационный механик (техник) по планеру и двигателям                                     Планер ва двигателлар бўйича авиация механиги (техник)  7232  П  2 — 6  ССПО                                   3310400                                           Planer va dvigatellar bo‘yicha aviatsiya mexanigi (texnik)  i   4
4    5 NaN   5.   5  C8                       Авиационный механик (техник) по приборам и электрооборудованию                              Приборлар ва электр жихозлар бўйича авиация механиги (техник)  7232  П  2 — 6  ССПО                                   3310400                                   Priborlar va elektr jixoz lar bo‘yicha aviatsiya mexanigi (texnik)  i   5
5    6 NaN   6.   6  C8                                    Авиационный механик (техник) по радиооборудованию                                            Радио жихозлар бўйича авиация механиги (техник)  7232  П  2 — 6  ССПО                                   3310400                                                 Radio jixoz lar bo‘yicha aviatsiya mexanigi (texnik)  i   6
6    7 NaN   7.   7  C8         Авиационный техник (механик) по парашютным и аварийно-спасательным средствам                     Парашют ва авария-қутқарув воситалари бўйича авиация техниги (механик)  7232  П  4 — 6  ССПО                                   3310400                        Parashyut va avariya-qutqaruv vositalari bo‘yicha aviatsiya texnigi (mexanik)  i   7
7    8 NaN   8.   8  C8                                    Авиационный техник по горюче-смазочным материалам                                          Ёқилғи-мойлаш материаллари бўйича авиация техниги  7232  П  3 — 5  ССПО                                   3310400                                             Yoqilg‘i-moylash materiallari bo‘yicha aviatsiya texnigi  i   8
8    9 NaN   9.   9  C8                                               Автоклавщик в гидролизном производстве                                                        Гидролиз ишлаб чиқаришда автоклавчи  8152  П  3 — 4  ССПО                                   3320400                                                              Gidroliz ishlab chiqarishda avtoklavchi  i   9
9   10 NaN  10.  10  C8                                    Автоклавщик в производстве стекла и стеклоизделий                                            Шиша ва шиша буюмлар ишлаб чиқаришда автоклавчи  8132  П  3 — 4  ССПО                 3340500, 3340200, 3320400                                             Shisha va shisha buyumlar ishlab chiqarishda avtoklavchi  i  10
10  11 NaN  11.  11  C8                              Автоклавщик в производстве теплоизоляционных материалов                                      Теплоизоляция материаллари ишлаб чиқаришда автоклавчи  8139  П      4  ССПО                                   3340500                                         Teploizolyatsiya materiallari ishlab chiqarishda avtoklavchi  i  11
11  12 NaN  12.  12  C8                                                      Автоклавщик литья под давлением                                                            Босим остида қуйиш автоклавчиси  8122  П      3  ССПО                                   3310300                                                                    Bosim ostida quyish avtoklavchisi  i  12
12  13 NaN  13.  13  C8                                                      Автоклавщик на запарке брикетов                                                            Брикетларни буғлаш автоклавчиси  8112  П      3  ССПО                                   3311600                                                                   Briketlarni Bug‘lash avtoklavchisi  i  13
13  14 NaN  14.  14  C8  Автоклавщик-сушильщик Аккумуляторных пластин в производстве свинцовых Аккумуляторов  Қўрғошинли аккумуляторлар ишлаб чиқаришда аккумулятор пластиналари автоклавчи-қуритувчиси  8290  П  2 — 3  ССПО                          3310300, 3320400  qo‘rg‘oshinli Akkumulyatorlar ishlab chiqarishda Akkumulyator plastinalari avtoklavchi-qurituvchisi  i  14
14  15 NaN  15.  15  C8                                                       Автоматчик вязальных автоматов                                                              Тўқиш автоматлари автоматчиси  8262  П  3 — 4  ССПО                                   3320900                                                                     To‘qish avtomatlari avtomatchisi  i  15
15  16 NaN  16.  16  C8                                                 Автоматчик игольно-платинных изделий                                                           Игна-платина буюмлар автоматчиси  8123  П  2 — 4  ССПО                                   3310300                                                                   Igna-platina buyumlar avtomatchisi  i  16
16  17 NaN  17.  17  C8                                                 Автоматчик картонажного производства                                                         Картонаж ишлаб чиқариш автоматчиси  8143  П  1 — 4  ССПО                          3340500, 3320800                                                               Kartonaj ishlab chiqarish avtomatchisi  i  17
17  18 NaN  18.  18  C8                                                   Автоматчик клеильных полуавтоматов                                                        Елимлаш яримавтоматлари автоматчиси  8142  П  3 — 5  ССПО  В зависимости от сферы применения знаний                                                               Elimlash yarimavtomatlari avtomatchisi  i  18
18  19 NaN  19.  19  C8                         Автоматчик на узловязальных и навивочных автоматах и станках                               Узеллар тўқиш ва эшиш автоматлари ва дастгоҳлари автоматчиси  8262  П  1 — 4  ССПО                          3320900, 3320200                                    Uzellar To‘qish va eshish avtomatlari va dastgohlari avtomatchisi  i  19
19  20 NaN  20.  20  C8                            Автоматчик по изготовлению деталей клавишных инструментов                                   Клавишали асбоблар деталларини тайёрлаш бўйича автоматчи  7312  П  2 — 4  ССПО                                   3151200                                       Klavishali asboblar detallarini tayyorlash bo‘yicha avtomatchi  i  20
20  21 NaN  21.  21  C8                                                        Автоматчик ремизных автоматов                                                               Ремиз автоматлар автоматчиси  8211  П  3 — 4  ССПО                                   3320200                                                                        Remiz avtomatlar avtomatchisi  i  21
21  22 NaN  22.  22  C8                                              Автоматчик холодно-высадочных автоматов                                                    Совитиб кўчириш автоматлари автоматчиси  8211  П  2 — 5  ССПО                                   3320300                                                          Sovitib ko‘chirish avtomatlari avtomatchisi  i  22
22  23 NaN  23.  23  C8                                                     Автоматчик шпиндельных автоматов                                                           Шпинделли автоматлар автоматчиси  8211  П  2 — 4  ССПО                                   3320900                                                                   Shpindelli avtomatlar avtomatchisi  i  23
23  24 NaN  24.  24  C8                                                  Автоматчик элементного производства                                                          Элемент ишлаб чиқариш автоматчиси  8211  П  1 — 4  ССПО                                   3310700                                                                Element ishlab chiqarish avtomatchisi  i  24
24  25 NaN  25.  25  C8                                                                         Агломератчик                                                                                Агломератчи  8112  П  3 — 6  ССПО                                   3311600                                                                                         Aglomeratchi  i  25
25  26 NaN  26.  26  C8                                                                           Агрегатчик                                                                                  Агрегатчи  8163  П  4 — 6  ССПО                                   3311900                                                                                           Agregatchi  i  26
26  27 NaN  27.  27  C8                                                                         Аквадировщик                                                                               Аквадирловчи  8223  П  3 — 4  ССПО                                   3310800                                                                                        Akvadirlovchi  i  27
27  28 NaN  28.  28  C8                                                                       Акклиматизатор                                                                           Акклиматизаторчи  7342  П  2 — 6  ССПО                                   3610600                                                                                    Akklimatizatorchi  i  28
28  29 NaN  29.  29  C8                                                                       Аккумуляторщик                                                                              Аккумуляторчи  7245  П  1 — 5  ССПО                          3310300, 3320400                                                                                      Akkumulyatorchi  i  29
29  30 NaN  30.  30  C8                                                                         Алундировщик                                                                               Алундирловчи  8223  П  2 — 5  ССПО                                   3310800                                                                                        Alundirlovchi  i  30
30  31 NaN  31.  31  C8                                                               Альпинист промышленный                                                                           Саноат алпинисти  3455  Т  3 — 5  ССПО                                   3610500                                                                                     Sanoat alpinisti  t  31
31  32 NaN  32.  32  C8                                                                        Алюминировщик                                                                                Алюминловчи  8223  П  2 — 6  ССПО                                   3310300                                                                                        Alyuminlovchi  i  32
32  33 NaN  33.  33  C8                                             Алюминировщик электротехнических изделий                                                        Электротехник буюмларни алюминловчи  8223  П  1 — 3  ССПО                                   3310700                                                               Elektrotexnik buyumlarni alyuminlovchi  i  33
33  34 NaN  34.  34  C8                                                                         Ангобировщик                                                                                  Ангобирчи  8134  П  2 — 5  ССПО                          3340500, 3340200                                                                                           Angobirchi  i  34
34  35 NaN  35.  35  C8                                          Ангобировщик санитарно-строительных изделий                                                    Санитария-қурилиш  буюмлари ангобирчиси  7324  П      5  ССПО                          3340500, 3340200                                                          Sanitariya-quqilish  buyumlari angobirchisi  i  35
35  36 NaN  36.  36  C8                                                                    Антенщик-мачтовик                                                                          Антенначи-мачтачи  7245  П  3 — 6  ССПО                                   3340200                                                                                 Antennachi-machtachi  i  36
36  37 NaN  37.  37  C8                                                                      Антикоррозийщик                                                                             Антикоррозиячи  8223  П  2 — 6  ССПО                          3310700, 3320400                                                                                     Antikorroziyachi  i  37
37  38 NaN  38.  38  C8                                                                           Аппаратчик                                                                                  Аппаратчи  8223  П  2 — 6  ССПО  В зависимости от сферы применения знаний                                                                                           Apparatchi  i  38
38  39 NaN  39.  39  C8                                                         Аппаратчик карбоксилирования                                                                   Карбоксиллаш аппаратчиси  8159  П  3 — 5  ССПО                                   3320400                                                                           KarbOqsillash apparatchisi  i  39
39  40 NaN  40.  40  C8                                                             Аппаратчик сульфирования                                                                     Сульфирлаш аппаратчиси  8159  П  3 — 6  ССПО                                   3320400                                                                              Sulfirlash apparatchisi  i  40
40  41 NaN  41.  41  C8                                                           Аппаратчик абсолютирования                                                                     Абсолютлаш аппаратчиси  8221  П      3  ССПО                                   3320400                                                                            Absolyutlash apparatchisi  i  41
41  42 NaN  42.  42  C8                                                                 Аппаратчик абсорбции                                                                      Абсорбция аппаратчиси  8154  П  2 — 6  ССПО                                   3320400                                                                             Absorbtsiya apparatchisi  i  42
42  43 NaN  43.  43  C8                                                                 Аппаратчик адсорбции                                                                      Адсорбция аппаратчиси  8154  П  2 — 6  ССПО                                   3320400                                                                             Adsorbtsiya apparatchisi  i  43
43  44 NaN  44.  44  C8                                                              Аппаратчик азотирования                                                                        Азотлаш аппаратчиси  8224  П  2 — 4  ССПО                                   3320400                                                                                Azotlash apparatchisi  i  44
44  45 NaN  45.  45  C8                                                                 Аппаратчик активации                                                                  Активлаштириш аппаратчиси  8159  П  3 — 5  ССПО                                   3320400                                                                         Aktivlashtirish apparatchisi  i  45
45  46 NaN  46.  46  C8                                                             Аппаратчик алкилирования                                                                     Алкилирлаш аппаратчиси  8159  П  3 — 6  ССПО                                   3320400                                                                             Alkilirlash apparatchisi  i  46
46  47 NaN  47.  47  C8                                                              Аппаратчик аминирования                                                                      Аминирлаш аппаратчиси  8159  П  3 — 5  ССПО                                   3320400                                                                              Aminirlash apparatchisi  i  47
47  48 NaN  48.  48  C8                                                                Аппаратчик аммонолиза                                                                      Аммонолиз аппаратчиси  8226  П  4 — 6  ССПО                                   3320400                                                                               Ammonoliz apparatchisi  i  48
48  49 NaN  49.  49  C8                                                              Аппаратчик ацилирования                                                                      Ацилирлаш аппаратчиси  8225  П  2 — 6  ССПО                                   3320400                                                                             Atsilirlash apparatchisi  i  49
49  50 NaN  50.  50  C8                                                      Аппаратчик балансовых установок                                                      Мувозанатловчи қурилмалар аппаратчиси  8232  П      4  ССПО                                   3320400                                                              Muvozanatlovchi qurilmalar apparatchisi  i  50

In [12]:
poss = ["Охранник", 
		"Дежурный", 
		"Старший смены охраны", 
		"Начальник охраны", 
		"Начальник службы охраны", 
		"Начальник охраны объекта", 
		"Начальник охраны (военизированной, пожарной, сторожевой)", 
		"Хранитель экспонатов", "Сторож",
		"Дежурный автостанции",
		"Дежурный администратор",
		"Дежурный аэропорта",
		"Дежурный бюро пропусков",
		"Дежурный гостиницы",
		"Дежурный диспетчер",
		"Дежурный инкассатор",
		"Дежурный камеры хранения",
		"Дежурный по вокзалу",
		"Дежурный по направлению",
		"Дежурный по общежитию",
		"Дежурный по полетам",
		"Дежурный по путям",
		"Дежурный по разъезду",
		"Дежурный по режиму",
		"Дежурный по станции",
		"Дежурный по электродепо",
		"Дежурный по электросвязи",
		"Дежурный службы движения",
		"Инспектор военизированной охраны",
		"Инспектор по охране природы",
		"Старший смены охраны"]
fltr = main[main["6"].isin(poss)]

In [16]:
fltr.to_excel('security_officer_names.xlsx', index=False, encoding='utf-8-sig')

/Users/ilkhom/miniconda3/lib/python3.9/site-packages/pandas/util/_decorators.py:211: FutureWarning: the 'encoding' keyword is deprecated and will be removed in a future version. Please take steps to stop the use of 'encoding'
  return func(*args, **kwargs)