In [7]:
import pandas as pd
import numpy as np
import psutil
from unidecode import unidecode
from fuzzywuzzy import fuzz
from collections import defaultdict
import json

# Check memory usage
def memory_usage():
    process = psutil.Process()
    mem_info = process.memory_info()
    return mem_info.rss / (1024 * 1024)  # Convert bytes to MB

print(f"Memory usage: {memory_usage()} MB")

Memory usage: 12.83203125 MB

In [8]:
# Set pandas display options
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.max_colwidth', None)  # Show full column width
pd.set_option('display.expand_frame_repr', False)  # Disable wrapping of rows

In [9]:
countryside_main_csv = pd.read_csv('./countryside_dump.csv', usecols=lambda x: x != "polygon")
countryside_main_csv.head(1)

      id               created_at   latitude  longitude      name               updated_at  district_id geometry_type  deleted
0  23029  2023-11-28 17:40:55.382  70.320386   41.75896  uzgarish  2023-11-28 17:40:55.382          419           NaN    False

In [16]:
import geopandas as gpd

countryside_main_geo = gpd.read_file('./Mahalla_11_11_2024.geojson')#,ignore_geometry=True)#pd.read_csv('./Tuman_11_11_2024.geojson')
countryside_main_geo['centroid'] = countryside_main_geo.geometry.centroid
countryside_main_geo['centroid_x'] = countryside_main_geo.centroid.x
countryside_main_geo['centroid_y'] = countryside_main_geo.centroid.y
countryside_main_geo.drop(columns=['geometry'], inplace=True)
countryside_main_geo.head(1)

/var/folders/ww/67t1k6ss6bqfd8tw6ntmpfgm0000gn/T/ipykernel_40091/105461824.py:4: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  countryside_main_geo['centroid'] = countryside_main_geo.geometry.centroid
/var/folders/ww/67t1k6ss6bqfd8tw6ntmpfgm0000gn/T/ipykernel_40091/105461824.py:5: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  countryside_main_geo['centroid_x'] = countryside_main_geo.centroid.x
/var/folders/ww/67t1k6ss6bqfd8tw6ntmpfgm0000gn/T/ipykernel_40091/105461824.py:6: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  countryside_main_geo['centroid_y'] = countryside_main_geo.centroid.y

   OBJECTID                    region_name  parent_code      district     code mahalla_nomi  mahalla_id Geonames_id  Qayta_chegaralangan  Shape_Length  Shape_Area                   centroid  centroid_x  centroid_y
0         1  Qoraqolpog'iston Respublikasi         1735  Nukus shahar  1735401   O'rnek MFY  1735401028  АPU:177810                  NaN      0.031806    0.000046  POINT (59.62071 42.44901)   59.620712   42.449009

In [19]:
countryside_main_csv.to_excel('countryside_csv.xlsx', index=False)
countryside_main_geo.to_excel('countryside_geo.xlsx', index=False)

In [9]:
district_main_csv = pd.read_csv('./district_dump.csv', usecols=lambda x: x != "polygon")
district_main_csv.head(1)

    id               created_at   latitude  longitude             name               updated_at  region_id  geometry_type  deleted
0  517  2023-08-03 15:52:14.546  40.503046  72.306111  Marxamat tumani  2023-12-25 16:41:43.091         35            NaN    False

In [10]:
district_main_csv.head(10)

    id               created_at   latitude  longitude                   name               updated_at  region_id  geometry_type  deleted
0  517  2023-08-03 15:52:14.546  40.503046  72.306111        Marxamat tumani  2023-12-25 16:41:43.091         35            NaN    False
1  611  2023-12-13 15:23:41.266  41.158200  69.441533  Yuqorichirchiq tumani  2023-12-25 17:37:03.557         29            NaN     True
2  614  2024-04-22 11:45:43.817  70.836913  40.432317                   TEST  2024-04-22 11:45:43.817         33            NaN    False
3  458  2023-08-03 15:52:00.864  40.567024  68.578033                   Test  2024-04-22 16:45:31.191         31            NaN     True
4  405  2023-08-03 15:51:55.043  69.166585  41.295745         Uchtepa tumani  2023-08-03 15:51:55.043         28            NaN    False
5  612  2023-12-15 10:34:14.469  39.481785  67.324905           Urgut tumani  2023-12-15 18:04:43.079         32            NaN     True
6  560   2023-08-03 15:52:21.19  39.726306  64.554945           Kogon tumani  2023-12-26 16:07:49.214         38            NaN    False
7  615  2024-04-22 16:24:17.009  40.412450  68.218231                    Jzx  2024-04-22 16:39:59.101         31            NaN     True
8  476  2023-08-03 15:52:04.892  67.176919  39.413383           Urgut tumani  2023-08-03 15:52:04.892         32            NaN    False
9  548  2023-08-03 15:52:19.804  37.841318  67.731519     Qumqo'rg'on tumani  2023-12-26 16:48:08.077         37            NaN    False

In [28]:
distr_csv_df = district_main_csv[district_main_csv['deleted'] == False]
distr_csv_df_sorted = distr_csv_df.sort_values(by='name')
distr_csv_df_sorted.to_excel('district_sorted.xlsx', index=False)

In [11]:
district_main_geo = gpd.read_file('./Tuman_11_11_2024.geojson',ignore_geometry=True)
district_main_geo.head(1)

Skipping field district_cad_id: unsupported OGR type: 10

   OBJECTID  parent_code     code       region_name        district  region_cad_id  Shape_Length  Shape_Area
0         1         1703  1703203  Andijon viloyati  Andijon tumani           17.0      1.688633    0.040525

In [12]:
district_main_geo.head(10)

   OBJECTID  parent_code     code       region_name           district  region_cad_id  Shape_Length  Shape_Area
0         1         1703  1703203  Andijon viloyati     Andijon tumani           17.0      1.688633    0.040525
1         2         1703  1703224  Andijon viloyati       Asaka tumani           17.0      1.259511    0.028683
2         3         1703  1703206  Andijon viloyati    Baliqchi tumani           17.0      1.652359    0.034678
3         4         1703  1703210  Andijon viloyati  Buloqboshi tumani           17.0      0.989023    0.019274
4         5         1703  1703209  Andijon viloyati     Bo‘ston tumani           17.0      0.758067    0.021426
5         6         1703  1703211  Andijon viloyati   Jalaquduq tumani           17.0      1.521801    0.039524
6         7         1703  1703214  Andijon viloyati    Izboskan tumani           17.0      1.105844    0.029423
7         8         1703  1703227  Andijon viloyati    Marxamat tumani           17.0      1.219814    0.034128
8         9         1703  1703202  Andijon viloyati   Oltinko‘l tumani           17.0      1.404261    0.022811
9        10         1703  1703232  Andijon viloyati   Paxtaobod tumani           17.0      1.250211    0.027358

In [27]:
district_main_geo_sorted = district_main_geo.sort_values(by='district')
district_main_geo_sorted.to_excel('./district_main_geo_sorted.xlsx', index=False)

In [29]:
district_main_geo_sorted

     OBJECTID  parent_code     code                    region_name                district  region_cad_id  Shape_Length  Shape_Area
201       204         1735  1735204  Qoraqalpog‘iston respublikasi         Amudaryo tumani           23.0      2.915235    0.114944
14         15         1703  1703401               Andijon viloyati          Andijon shahar           17.0      0.944401    0.006908
0           1         1703  1703203               Andijon viloyati          Andijon tumani           17.0      1.688633    0.040525
97         98         1722  1722202           Surxondaryo viloyati            Angor tumani           19.0      1.480651    0.039003
146       147         1727  1727407              Toshkent viloyati                  Angren           11.0      1.667259    0.016474
29         30         1708  1708201                Jizzax viloyati          Arnasoy tumani           13.0      1.262834    0.052397
1           2         1703  1703224               Andijon viloyati            Asaka tumani           17.0      1.259511    0.028683
2           3         1703  1703206               Andijon viloyati         Baliqchi tumani           17.0      1.652359    0.034678
98         99         1722  1722203           Surxondaryo viloyati         Bandixon tumani           19.0      1.709801    0.066248
41         42         1708  1708204                Jizzax viloyati           Baxmal tumani           13.0      2.782146    0.195320
147       148         1727  1727413              Toshkent viloyati                 Bekobod           11.0      0.450332    0.003690
155       156         1727  1727220              Toshkent viloyati          Bekobod tumani           11.0      2.191990    0.079597
130       131         1726  1726264                Toshkent shahri         Bektemir tumani           10.0      0.294427    0.003501
187       190         1735  1735207  Qoraqalpog‘iston respublikasi          Beruniy tumani           23.0      4.398848    0.429239
164       165         1730  1730215              Farg‘ona viloyati         Beshariq tumani           15.0      1.575168    0.079760
163       164         1730  1730209              Farg‘ona viloyati          Bog‘dod tumani           15.0      1.176177    0.035468
176       177         1733  1733204                Xorazm viloyati           Bog‘ot tumani           22.0      1.236180    0.047832
122       123         1724  1724212              Sirdaryo viloyati          Boyovut tumani           12.0      1.161150    0.055417
99        100         1722  1722204           Surxondaryo viloyati           Boysun tumani           19.0      3.616418    0.345382
141       142         1727  1727228              Toshkent viloyati            Bo‘ka tumani           11.0      1.710535    0.063029
4           5         1703  1703209               Andijon viloyati          Bo‘ston tumani           17.0      0.758067    0.021426
142       143         1727  1727224              Toshkent viloyati       Bo‘stonliq tumani           11.0      6.534360    0.532767
202       205         1735  1735209  Qoraqalpog‘iston respublikasi         Bo‘zatov tumani           23.0      2.642660    0.217447
3           4         1703  1703210               Andijon viloyati       Buloqboshi tumani           17.0      0.989023    0.019274
83         84         1718  1718206             Samarqand viloyati        Bulung‘ur tumani           14.0      2.184321    0.080700
166       167         1730  1730212              Farg‘ona viloyati          Buvayda tumani           15.0      1.098389    0.030193
16         17         1706  1706401                Buxoro viloyati           Buxoro shahar           20.0      0.604672    0.008431
18         19         1706  1706207                Buxoro viloyati           Buxoro tumani           20.0      3.464037    0.138459
131       132         1726  1726294                Toshkent shahri        Chilonzor tumani           10.0      0.344108    0.003275
193       196         1735  1735240  Qoraqalpog‘iston respublikasi          Chimboy tumani           23.0      1.952107    0.155284
145       146         1727  1727256              Toshkent viloyati           Chinoz tumani           11.0      1.286466    0.036125
150       151         1727  1727419              Toshkent viloyati                Chirchiq           11.0      0.462841    0.004734
57         58         1710  1710242           Qashqadaryo viloyati        Chiroqchi tumani           18.0      2.523105    0.118799
76         77         1714  1714236              Namangan viloyati          Chortoq tumani           16.0      1.747664    0.042959
77         78         1714  1714237              Namangan viloyati            Chust tumani           16.0      1.871213    0.098665
165       166         1730  1730236              Farg‘ona viloyati         Dang‘ara tumani           15.0      1.278989    0.045776
43         44         1710  1710212           Qashqadaryo viloyati       Dehqonobod tumani           18.0      4.645908    0.409138
100       101         1722  1722210           Surxondaryo viloyati            Denov tumani           19.0      1.886604    0.085164
35         36         1708  1708215                Jizzax viloyati         Do‘stlik tumani           13.0      1.251503    0.047941
195       198         1735  1735250  Qoraqalpog‘iston respublikasi        Ellikkala tumani           23.0      6.441990    0.590223
162       163         1730  1730401              Farg‘ona viloyati         Farg‘ona shahri           15.0      0.717647    0.011437
171       172         1730  1730233              Farg‘ona viloyati         Farg‘ona tumani           15.0      2.790334    0.062910
38         39         1708  1708235                Jizzax viloyati           Forish tumani           13.0      6.600747    0.992575
172       173         1730  1730238              Farg‘ona viloyati           Furqat tumani           15.0      1.207468    0.031889
120       121         1724  1724401              Sirdaryo viloyati                Guliston           12.0      0.568322    0.004337
112       113         1724  1724220              Sirdaryo viloyati         Guliston tumani           12.0      1.504763    0.036897
177       178         1733  1733208                Xorazm viloyati           Gurlan tumani           22.0      1.285808    0.047899
33         34         1708  1708209                Jizzax viloyati       G‘allaorol tumani           13.0      2.679147    0.207188
28         29         1706  1706215                Buxoro viloyati        G‘ijduvon tumani           20.0      4.602606    0.404022
68         69         1712  1712412                Navoiy viloyati         G‘ozg‘on shahri           21.0      1.072408    0.063462
53         54         1710  1710207           Qashqadaryo viloyati           G‘uzor tumani           18.0      3.203464    0.274169
85         86         1718  1718212             Samarqand viloyati         Ishtixon tumani           14.0      2.537086    0.075753
6           7         1703  1703214               Andijon viloyati         Izboskan tumani           17.0      1.105844    0.029423
5           6         1703  1703211               Andijon viloyati        Jalaquduq tumani           17.0      1.521801    0.039524
101       102         1722  1722212           Surxondaryo viloyati      Jarqo‘rg‘on tumani           19.0      2.965922    0.113480
40         41         1708  1708401                Jizzax viloyati           Jizzax shahri           13.0      1.324583    0.011082
84         85         1718  1718209             Samarqand viloyati           Jomboy tumani           14.0      1.776863    0.057727
20         21         1706  1706246                Buxoro viloyati           Jondor tumani           20.0      6.373855    0.534025
60         61         1712  1712234                Navoiy viloyati          Karmana tumani           21.0      2.529708    0.104937
44         45         1710  1710237           Qashqadaryo viloyati            Kasbi tumani           18.0      2.028010    0.076753
95         96         1718  1718406             Samarqand viloyati           Kattaqo‘rg‘on           14.0      0.520002    0.004634
87         88         1718  1718215             Samarqand viloyati    Kattaqo‘rg‘on tumani           14.0      5.552775    0.144781
203       206         1735  1735212  Qoraqalpog‘iston respublikasi          Kegeyli tumani           23.0      2.025427    0.101473
45         46         1710  1710232           Qashqadaryo viloyati            Kitob tumani           18.0      3.197898    0.181173
56         57         1710  1710240           Qashqadaryo viloyati         Ko'kdala tumani           18.0      3.382483    0.178337
17         18         1706  1706403                Buxoro viloyati            Kogon shahar           20.0      0.238472    0.001672
21         22         1706  1706219                Buxoro viloyati            Kogon tumani           20.0      1.463784    0.052633
58         59         1712  1712211                Navoiy viloyati          Konimex tumani           21.0     12.536292    1.726425
46         47         1710  1710229           Qashqadaryo viloyati            Koson tumani           18.0      2.712413    0.192763
75         76         1714  1714207              Namangan viloyati         Kosonsoy tumani           16.0      1.557879    0.052590
161       162         1730  1730412              Farg‘ona viloyati        Marg‘ilon shahar           15.0      0.631385    0.005051
7           8         1703  1703227               Andijon viloyati         Marxamat tumani           17.0      1.219814    0.034128
69         70         1714  1714204              Namangan viloyati        Mingbuloq tumani           16.0      1.908988    0.064239
42         43         1710  1710233           Qashqadaryo viloyati        Mirishkor tumani           18.0      3.403107    0.321998
134       135         1726  1726273                Toshkent shahri          Mirobod tumani           10.0      0.266172    0.001774
31         32         1708  1708223                Jizzax viloyati       Mirzacho‘l tumani           13.0      1.302586    0.053429
113       114         1724  1724228              Sirdaryo viloyati        Mirzaobod tumani           12.0      1.393641    0.071392
124       125         1726  1726269                Toshkent shahri   Mirzo ulug‘bek tumani           10.0      0.605354    0.006404
190       193         1735  1735222  Qoraqalpog‘iston respublikasi          Mo‘ynoq tumani           23.0      9.767684    4.251136
47         48         1710  1710234           Qashqadaryo viloyati          Muborak tumani           18.0      4.043789    0.321357
106       107         1722  1722207           Surxondaryo viloyati         Muzrabot tumani           19.0      2.160160    0.076019
80         81         1714  1714401              Namangan viloyati         Namangan shahri           16.0      1.116694    0.019719
73         74         1714  1714212              Namangan viloyati         Namangan tumani           16.0      0.918583    0.021986
88         89         1718  1718218             Samarqand viloyati           Narpay tumani           14.0      1.425950    0.046736
59         60         1712  1712230                Navoiy viloyati         Navbahor tumani           21.0      2.739556    0.157345
66         67         1712  1712401                Navoiy viloyati           Navoiy shahar           21.0      0.548442    0.006377
48         49         1710  1710235           Qashqadaryo viloyati           Nishon tumani           18.0      2.645285    0.218219
74         75         1714  1714216              Namangan viloyati            Norin tumani           16.0      1.499099    0.022578
198       201         1735  1735401  Qoraqalpog‘iston respublikasi                   Nukus           23.0      1.161771    0.023186
188       191         1735  1735225  Qoraqalpog‘iston respublikasi            Nukus tumani           23.0      3.356228    0.104304
151       152         1727  1727401              Toshkent viloyati               Nurafshon           11.0      0.281197    0.003753
89         90         1718  1718235             Samarqand viloyati          Nurobod tumani           14.0      7.907767    0.508449
61         62         1712  1712238                Navoiy viloyati           Nurota tumani           21.0      4.768633    0.626485
149       150         1727  1727415              Toshkent viloyati               Ohangaron           11.0      0.252530    0.001939
153       154         1727  1727212              Toshkent viloyati        Ohangaron tumani           11.0      5.354422    0.332846
148       149         1727  1727404              Toshkent viloyati                 Olmaliq           11.0      1.116057    0.014165
126       127         1726  1726280                Toshkent shahri          Olmazor tumani           10.0      0.276502    0.003636
22         23         1706  1706204                Buxoro viloyati             Olot tumani           20.0      2.710649    0.338078
173       174         1730  1730203              Farg‘ona viloyati         Oltiariq tumani           15.0      1.758459    0.066560
8           9         1703  1703202               Andijon viloyati        Oltinko‘l tumani           17.0      1.404261    0.022811
107       108         1722  1722201           Surxondaryo viloyati         Oltinsoy tumani           19.0      1.941291    0.060167
90         91         1718  1718203             Samarqand viloyati          Oqdaryo tumani           14.0      1.388012    0.039950
114       115         1724  1724206              Sirdaryo viloyati          Oqoltin tumani           12.0      1.033824    0.052809
143       144         1727  1727206              Toshkent viloyati       Oqqo‘rg‘on tumani           11.0      1.704909    0.043333
140       141         1727  1727253              Toshkent viloyati    O‘rtachirchiq tumani           11.0      2.145526    0.046066
158       159         1730  1730230              Farg‘ona viloyati      O‘zbekiston tumani           15.0      1.546024    0.071969
144       145         1727  1727249              Toshkent viloyati          Parkent tumani           11.0      2.453443    0.119314
92         93         1718  1718227             Samarqand viloyati      Pastdarg‘om tumani           14.0      1.944071    0.091732
93         94         1718  1718230             Samarqand viloyati         Paxtachi tumani           14.0      2.527313    0.144788
32         33         1708  1708228                Jizzax viloyati         Paxtakor tumani           13.0      1.104269    0.039908
9          10         1703  1703232               Andijon viloyati        Paxtaobod tumani           17.0      1.250211    0.027358
91         92         1718  1718224             Samarqand viloyati          Payariq tumani           14.0      3.193881    0.138254
23         24         1706  1706240                Buxoro viloyati           Peshku tumani           20.0      6.677911    0.923939
70         71         1714  1714219              Namangan viloyati              Pop tumani           16.0      4.454668    0.324375
154       155         1727  1727250              Toshkent viloyati           Pskent tumani           11.0      3.271944    0.080505
51         52         1710  1710220           Qashqadaryo viloyati          Qamashi tumani           18.0      5.548257    0.272878
196       199         1735  1735218  Qoraqalpog‘iston respublikasi        Qanliko‘l tumani           23.0      1.668381    0.084142
54         55         1710  1710401           Qashqadaryo viloyati                  Qarshi           18.0      1.183441    0.009292
52         53         1710  1710224           Qashqadaryo viloyati           Qarshi tumani           18.0      3.775176    0.093965
156       157         1727  1727248              Toshkent viloyati           Qibray tumani           11.0      1.929004    0.050795
138       139         1727  1727233              Toshkent viloyati     Qiyichirchiq tumani           11.0      2.046659    0.060948
65         66         1712  1712216                Navoiy viloyati        Qiziltepa tumani           21.0      2.981478    0.234248
102       103         1722  1722215           Surxondaryo viloyati          Qiziriq tumani           19.0      1.350791    0.040508
27         28         1706  1706230                Buxoro viloyati         Qorako‘l tumani           20.0      5.123246    0.745824
197       200         1735  1735211  Qoraqalpog‘iston respublikasi        Qorao‘zak tumani           23.0      5.882968    0.645764
26         27         1706  1706232                Buxoro viloyati     Qorovulbozor tumani           20.0      2.214644    0.228855
200       203         1735  1735215  Qoraqalpog‘iston respublikasi       Qo‘ng‘irot tumani           23.0     17.606573    8.440404
159       160         1730  1730405              Farg‘ona viloyati           Qo‘qon shahri           15.0      0.495127    0.006720
13         14         1703  1703220               Andijon viloyati     Qo‘rg‘ontepa tumani           17.0      2.216549    0.046324
183       185         1733  1733212                Xorazm viloyati      Qo‘shko‘pir tumani           22.0      1.495356    0.058439
86         87         1718  1718216             Samarqand viloyati       Qo‘shrabot tumani           14.0      3.242672    0.229125
157       158         1730  1730206              Farg‘ona viloyati        Qo‘shtepa tumani           15.0      1.192500    0.039114
105       106         1722  1722214           Surxondaryo viloyati      Qumqo‘rg‘on tumani           19.0      4.889587    0.236163
168       169         1730  1730218              Farg‘ona viloyati             Quva tumani           15.0      1.471030    0.046429
160       161         1730  1730408              Farg‘ona viloyati          Quvasoy shahri           15.0      1.308154    0.027957
174       175         1730  1730224              Farg‘ona viloyati          Rishton tumani           15.0      1.214161    0.032774
24         25         1706  1706242                Buxoro viloyati          Romitan tumani           20.0      5.602423    0.432611
96         97         1718  1718401             Samarqand viloyati               Samarqand           14.0      1.492396    0.011834
81         82         1718  1718233             Samarqand viloyati        Samarqand tumani           14.0      2.522457    0.049086
115       116         1724  1724226              Sirdaryo viloyati          Sardoba tumani           12.0      1.084495    0.060184
108       109         1722  1722217           Surxondaryo viloyati        Sariosiyo tumani           19.0      3.840954    0.381124
116       117         1724  1724216              Sirdaryo viloyati       Sayxunobod tumani           12.0      1.478833    0.048022
55         56         1710  1710405           Qashqadaryo viloyati              Shahrisabz           18.0      0.382348    0.004807
49         50         1710  1710245           Qashqadaryo viloyati       Shahrisabz tumani           18.0      3.666709    0.168154
34         35         1708  1708212                Jizzax viloyati  Sharof Rashidov tumani           13.0      3.497891    0.138024
12         13         1703  1703230               Andijon viloyati        Shaxrixon tumani           17.0      1.310535    0.030796
133       134         1726  1726277                Toshkent shahri     Shayxontohur tumani           10.0      0.325375    0.002910
110       111         1722  1722223           Surxondaryo viloyati         Sherobod tumani           19.0      3.271717    0.268288
119       120         1724  1724410              Sirdaryo viloyati                  Shirin           12.0      0.343598    0.002007
25         26         1706  1706258                Buxoro viloyati        Shofirkon tumani           20.0      3.409079    0.397605