In [2]:
import pandas as pd

In [8]:
def decode_text(text):
    """Decode text from 'latin1' to 'utf-8'."""
    return text.encode('latin1').decode('utf-8')

def load_and_decode_csv(file_path):
    """Load and decode a CSV file, then parse it into a pandas DataFrame."""
    # Load the CSV file with 'latin1' encoding
    df = pd.read_csv(file_path, encoding='latin1')
    
    # Decode each string in the DataFrame
    for column in df.columns:
        df[column] = df[column].apply(lambda x: decode_text(x) if isinstance(x, str) else x)
    
    return df

# Example usage
file_path = 'select.csv'
df = load_and_decode_csv(file_path)
print(df.head())

   LITSO_ID  BRANCH_ID           R2          R3             R4  \
0    146594          2       АБАЛЯН       АРМЭН  АЛЕКСАНДРОВИЧ
1   5719135          8      АБДИРОВ  МАДАМИНЖОН    МИРЗАЛИЕВИЧ
2   6273990          3  АБДУКАРИМОВ   РУСТАМЖОН  ТУЛАНДЖАНОВИЧ
3   5111574         12  АБДУКАРИМОВ       ЗОКИР   МАМАЮСУПОВИЧ
4   2634799         12    АБДУЛЛАЕВ      ФАРХОД   САРИМСАКОВИЧ

                    R5  R8                R10                   R11      R12  \
0  1988-01-26 00:00:00  AA                NaN                   NaN  ТАШКЕНТ
1  1970-03-02 00:00:00  AC  НАМАНГАНСКАЯ ОБЛ.  ЯНГИКУРГАНСКИЙ РАЙОН      NaN
2  1980-08-10 00:00:00  CL   АНДИЖАНСКАЯ ОБЛ.                   NaN      NaN
3  1970-05-10 00:00:00  AC   ТАШКЕНТСКАЯ ОБЛ.                   NaN      NaN
4  1963-12-31 00:00:00  AB   ТАШКЕНТСКАЯ ОБЛ.                   NaN      NaN

   ...         PINFL                             TB_ID       R2_LAT  \
0  ...  3.260188e+13  DDAC2FD8007C4FBDBF59990DA6B5C4D6      ABALYAN
1  ...  3.020370e+13  F4F54F016E094D59A74D82B819D9FBFD      ABDIROV
2  ...  3.100880e+13                          27019057  ABDUKARIMOV
3  ...  3.100571e+13  9A901B67726F47E79B836271650F3410  ABDUKARIMOV
4  ...  3.311264e+13  D138E76FD3934EB6A89B082D7FF323A7   ABDULLAYEV

       R3_LAT          R4_LAT      R3_CYR         R4_CYR       R2_CYR DRE  R__
0       ARMEN  ALEKSANDROVICH       АРМЭН  АЛЕКСАНДРОВИЧ       АБАЛЯН NaN  148
1  MADAMINJON   MIRZALIYEVICH  МАДАМИНЖОН    МИРЗАЛИЕВИЧ      АБДИРОВ NaN  370
2   RUSTAMJON  TULANDJANOVICH   РУСТАМЖОН  ТУЛАНДЖАНОВИЧ  АБДУКАРИМОВ NaN  556
3       ZOKIR  MAMAYUSUPOVICH       ЗОКИР   МАМАЮСУПОВИЧ  АБДУКАРИМОВ NaN  318
4      FARHOD   SARIMSAQOVICH      ФАРҲОД   САРИМСАҚОВИЧ    АБДУЛЛАЕВ NaN  293

[5 rows x 79 columns]

In [10]:
date_reformated = df.copy()
date_reformated['R5'] = pd.to_datetime(df['R5']).dt.strftime('%d.%m.%Y')
date_reformated.head()

,LITSO_ID,BRANCH_ID,R2,R3,R4,R5,R8,R10,R11,R12,...,PINFL,TB_ID,R2_LAT,R3_LAT,R4_LAT,R3_CYR,R4_CYR,R2_CYR,DRE,R__
0,146594,2,АБАЛЯН,АРМЭН,АЛЕКСАНДРОВИЧ,26.01.1988,AA,NaN,NaN,ТАШКЕНТ,...,3.260188e+13,DDAC2FD8007C4FBDBF59990DA6B5C4D6,ABALYAN,ARMEN,ALEKSANDROVICH,АРМЭН,АЛЕКСАНДРОВИЧ,АБАЛЯН,NaN,148
1,5719135,8,АБДИРОВ,МАДАМИНЖОН,МИРЗАЛИЕВИЧ,02.03.1970,AC,НАМАНГАНСКАЯ ОБЛ.,ЯНГИКУРГАНСКИЙ РАЙОН,NaN,...,3.020370e+13,F4F54F016E094D59A74D82B819D9FBFD,ABDIROV,MADAMINJON,MIRZALIYEVICH,МАДАМИНЖОН,МИРЗАЛИЕВИЧ,АБДИРОВ,NaN,370
2,6273990,3,АБДУКАРИМОВ,РУСТАМЖОН,ТУЛАНДЖАНОВИЧ,10.08.1980,CL,АНДИЖАНСКАЯ ОБЛ.,NaN,NaN,...,3.100880e+13,27019057,ABDUKARIMOV,RUSTAMJON,TULANDJANOVICH,РУСТАМЖОН,ТУЛАНДЖАНОВИЧ,АБДУКАРИМОВ,NaN,556
3,5111574,12,АБДУКАРИМОВ,ЗОКИР,МАМАЮСУПОВИЧ,10.05.1970,AC,ТАШКЕНТСКАЯ ОБЛ.,NaN,NaN,...,3.100571e+13,9A901B67726F47E79B836271650F3410,ABDUKARIMOV,ZOKIR,MAMAYUSUPOVICH,ЗОКИР,МАМАЮСУПОВИЧ,АБДУКАРИМОВ,NaN,318
4,2634799,12,АБДУЛЛАЕВ,ФАРХОД,САРИМСАКОВИЧ,31.12.1963,AB,ТАШКЕНТСКАЯ ОБЛ.,NaN,NaN,...,3.311264e+13,D138E76FD3934EB6A89B082D7FF323A7,ABDULLAYEV,FARHOD,SARIMSAQOVICH,ФАРҲОД,САРИМСАҚОВИЧ,АБДУЛЛАЕВ,NaN,293

In [15]:
df_full = pd.read_excel('recidivist.xlsx')
df_full.head()

,п/п,НОМЕР_КАРТОЧКИ,ПОДРАЗДЕЛЕНИЕ,НАЛИЧИЕ_Ф1,ФАМИЛИЯ,ИМЯ,ОТЧЕСТВО,ДАТА_РОЖДЕНИЯ,ДАТА_ВВОДА,ОРГАН_Н,КАТЕГОРИЯ_УЧЕТ_Н,МЕСТОНАХОЖДЕН_Н
0,1,144503,ТОШКЕНТ (ШАҲАР),Да,АБАЛЯН,АРМЭН,АЛЕКСАНДРОВИЧ,26.01.1988,18.04.2023,ЯККАСАРОЙ ТУМАНИ ИИО ФМБ,ЎТА ХАВФЛИ РЕЦИДИВИСТ,ОЗОДЛИКДА
1,2,815254,ТОШКЕНТ (ВИЛ),Да,АБДАЛИЕВ,ШУХРАТЖОН,АБДИЛЛАЖОНОВИЧ,08.12.1975,28.02.2015,ОХАНГАРОН ТУМАНИ ИИБ,ЎТА ХАВФЛИ РЕЦИДИВИСТ,ОЗОДЛИКДА
2,3,824488,ТОШКЕНТ (ВИЛ),Да,АБДИГАППАРОВ,МАКСУДЖОН,МУХАМАДАЛИЕВИЧ,07.09.1982,31.01.2015,ОҚҚЎРҒОН ТУМАНИ ИИБ,ЎТА ХАВФЛИ РЕЦИДИВИСТ,ОЗОДЛИКДА
3,4,50566,ЖИЗЗАХ,Да,АБДИКАДИРОВ,ИКРОМ,УРАЗКУЛОВИЧ,20.10.1974,27.09.2010,ҒАЛЛААОРОЛ ТУМАНИ ИИБ,ЎТА ХАВФЛИ РЕЦИДИВИСТ,ОЗОДЛИКДА
4,5,606336,НАМАНГАН,Да,АБДИКОДИРОВ,МУРОТЖОН,БАРХОМЖОНОВИЧ,04.07.1980,30.10.2014,ПОП ТУМАНИ ИИБ,ЎТА ХАВФЛИ РЕЦИДИВИСТ,ОЗОДЛИКДА

In [18]:
def find_unique_rows(df1, df2):
    # Merge df1 with df2 using a left join to keep all rows from df1
    merged_df = df1.merge(df2, on=['ФАМИЛИЯ', 'ИМЯ', 'ОТЧЕСТВО', 'ДАТА_РОЖДЕНИЯ'], how='left', indicator=True)
    # Filter rows where df2 didn't have a matching row (i.e., '_merge' column is 'left_only')
    unique_df = merged_df[merged_df['_merge'] == 'left_only'].drop(columns=['_merge'])
    return unique_df

date_reformated.rename(columns={'R2':'ФАМИЛИЯ','R3':'ИМЯ','R4':'ОТЧЕСТВО','R5':'ДАТА_РОЖДЕНИЯ'}, inplace=True)
# Find unique rows in df1 that are not in df2
unique_df = find_unique_rows(df_full, date_reformated)
print(unique_df)

       п/п  НОМЕР_КАРТОЧКИ  ПОДРАЗДЕЛЕНИЕ НАЛИЧИЕ_Ф1       ФАМИЛИЯ  \
1        2          815254  ТОШКЕНТ (ВИЛ)         Да      АБДАЛИЕВ
2        3          824488  ТОШКЕНТ (ВИЛ)         Да  АБДИГАППАРОВ
3        4           50566         ЖИЗЗАХ         Да   АБДИКАДИРОВ
4        5          606336       НАМАНГАН         Да   АБДИКОДИРОВ
5        6         1337531     СУРХОНДАРЁ         Да   АБДИНАЗАРОВ
...    ...             ...            ...        ...           ...
2678  2679         1280700         ХОРАЗМ         Да        ЯМУТОВ
2679  2680          723201      САМАРКАНД         Да         ЯРИЕВ
2680  2681          100559      ҚАШҚАДАРЁ         Да       ЯРКУЛОВ
2681  2682          878721  ТОШКЕНТ (ВИЛ)        Нет        ЯРОВОЙ
2683  2684         1017075        ФАРҒОНА         Да        ЯХШИЕВ

             ИМЯ        ОТЧЕСТВО ДАТА_РОЖДЕНИЯ  ДАТА_ВВОДА  \
1      ШУХРАТЖОН  АБДИЛЛАЖОНОВИЧ    08.12.1975  28.02.2015
2      МАКСУДЖОН  МУХАМАДАЛИЕВИЧ    07.09.1982  31.01.2015
3          ИКРОМ     УРАЗКУЛОВИЧ    20.10.1974  27.09.2010
4       МУРОТЖОН   БАРХОМЖОНОВИЧ    04.07.1980  30.10.2014
5     АБДУСАТТОР  АБДИГАППАРОВИЧ    05.10.1968  27.05.2020
...          ...             ...           ...         ...
2678     БАХТИЯР    МАТЬЯКУБОВИЧ    05.06.1971  02.12.2019
2679      ШЕРАЛИ        ЭШБОЕВИЧ    18.10.1963  17.02.2018
2680      БАХРОН       БОЛТАЕВИЧ    03.01.1971  07.11.2013
2681      ВИКТОР       ВАСИЛЕВИЧ    13.04.1955  28.01.2015
2683       АСРОР        АЗИЗОВИЧ    17.09.1974  25.12.2015

                    ОРГАН_Н  ... PINFL TB_ID  R2_LAT  R3_LAT R4_LAT R3_CYR  \
1      ОХАНГАРОН ТУМАНИ ИИБ  ...   NaN   NaN     NaN     NaN    NaN    NaN
2       ОҚҚЎРҒОН ТУМАНИ ИИБ  ...   NaN   NaN     NaN     NaN    NaN    NaN
3     ҒАЛЛААОРОЛ ТУМАНИ ИИБ  ...   NaN   NaN     NaN     NaN    NaN    NaN
4            ПОП ТУМАНИ ИИБ  ...   NaN   NaN     NaN     NaN    NaN    NaN
5           УЗУН ТУМАНИ ИИБ  ...   NaN   NaN     NaN     NaN    NaN    NaN
...                     ...  ...   ...   ...     ...     ...    ...    ...
2678   УРГАНЧ ШАҲАР ИИО ФМБ  ...   NaN   NaN     NaN     NaN    NaN    NaN
2679     ПАХТАЧИ ТУМАНИ ИИБ  ...   NaN   NaN     NaN     NaN    NaN    NaN
2680       КОСОН ТУМАНИ ИИБ  ...   NaN   NaN     NaN     NaN    NaN    NaN
2681   БЎСТОНЛИҚ ТУМАНИ ИИБ  ...   NaN   NaN     NaN     NaN    NaN    NaN
2683    ҚЎҚОН ШАҲАР ИИО ФМБ  ...   NaN   NaN     NaN     NaN    NaN    NaN

     R4_CYR R2_CYR  DRE  R__
1       NaN    NaN  NaN  NaN
2       NaN    NaN  NaN  NaN
3       NaN    NaN  NaN  NaN
4       NaN    NaN  NaN  NaN
5       NaN    NaN  NaN  NaN
...     ...    ...  ...  ...
2678    NaN    NaN  NaN  NaN
2679    NaN    NaN  NaN  NaN
2680    NaN    NaN  NaN  NaN
2681    NaN    NaN  NaN  NaN
2683    NaN    NaN  NaN  NaN

[2023 rows x 87 columns]

In [19]:
unique_df.to_excel('not_included.xlsx')